apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rmyergseg-nodejs 
  janus-idp.io/tekton: rmyergseg-nodejs
  backstage.io/kubernetes-id: rmyergseg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rmyergseg-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml